version: "3"
services:
  redis:
    image: redis:7.0-alpine
    command: redis-server
    volumes:
      - redis:/data
  db:
    image: mysql:8.0.35
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: chat_app_dev
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create && rails db:migrate && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  redis:
  mysql_data:
  esdata01:
  
  
